### ISSUE TITLE
socket is closed but it is not releasing the port properly

### ISSUE THREAD

**Issue by 23paras** [JacORB/JacORB#237]
@rnc
@alkasingheci
Hi ,
I am facing one problem in jacorb -

org.omg.CORBA.COMM_FAILURE: IOException: java.net.SocketException: Socket closed vmcid: 0x0 minor code: 0 completed: No
at org.jacorb.orb.etf.ConnectionBase.to_COMM_FAILURE(ConnectionBase.java:153)
at org.jacorb.orb.iiop.IIOPConnection.handleCommFailure(IIOPConnection.java:79)
at org.jacorb.orb.etf.StreamConnectionBase.flush(StreamConnectionBase.java:227)
at org.jacorb.orb.giop.ServerGIOPConnection.sendCloseConnection(ServerGIOPConnection.java:152)
at org.jacorb.orb.giop.ServerGIOPConnection.tryClose(ServerGIOPConnection.java:97)
at org.jacorb.orb.giop.GIOPConnectionManager.shutdown(GIOPConnectionManager.java:228)
at org.jacorb.orb.ORB.shutdown(ORB.java:2386)

Here it is showing socket is closed but it is not releasing the port properly. It is close_wait state .Please suggest what do to in oreder to fix this problem .

Thanks
Paras jain

**Comment by rnc** [comment]
Can you supply a test case please showing the issue?

**Comment by 23paras** [comment]
it is happening when we are closing the connection to the peer but at the same time we lost the connection to the peer.

**Comment by rnc** [comment]
Have you called _release on the client object? Can you provide a program demonstrating the issue?

**Comment by 23paras** [comment]
@rnc 
@alkasingheci

This is not happening always .Some time we are facing close_wait issue .Following is the sample code -

	private static ORB theORB;
	if (theORB != null) {
        try {
            theORB.shutdown(true);
            theORB.destroy();
        } catch (Exception e) {
            System.out.println("Error in closing theORB", e);
        }
    }

**Comment by rnc** [comment]
Is that your entire program? What JDK are you running on ? On what system?

**Comment by 23paras** [comment]
Some time we are also facing this issue while sending request to the peer .Following is the trace -
SEVERE Failed to write GIOP message due to COMM_FAILURE, in ClientGIOPConnection to 100.74.24.35:6337 (64cbdba4)
org.omg.CORBA.COMM_FAILURE: IOException: java.net.SocketException: Broken pipe  vmcid: 0x0  minor code: 0  completed: No
	at org.jacorb.orb.etf.ConnectionBase.to_COMM_FAILURE(ConnectionBase.java:153)
	at org.jacorb.orb.iiop.IIOPConnection.handleCommFailure(IIOPConnection.java:79)
	at org.jacorb.orb.etf.StreamConnectionBase.flush(StreamConnectionBase.java:227)
	at org.jacorb.orb.giop.GIOPConnection.sendMessage(GIOPConnection.java:1097)
	at org.jacorb.orb.giop.GIOPConnection.sendRequest(GIOPConnection.java:1022)
	at org.jacorb.orb.giop.ClientConnection.sendRequest(ClientConnection.java:309)
	at org.jacorb.orb.giop.ClientConnection.sendRequest(ClientConnection.java:290)
	at org.jacorb.orb.Delegate._invoke_internal(Delegate.java:1373)
	at org.jacorb.orb.Delegate.invoke_internal(Delegate.java:1210)
	at org.jacorb.orb.Delegate.invoke(Delegate.java:1197)
	at org.omg.CORBA.portable.ObjectImpl._invoke(ObjectImpl.java:475)

**Comment by 23paras** [comment]
jdk version -

java version "1.8.0_65"
Java(TM) SE Runtime Environment (build 1.8.0_65-b17)
Java HotSpot(TM) 64-Bit Server VM (build 25.65-b01, mixed mode)

System -

Solaris

**Comment by rnc** [comment]
I don't have access to Solaris, but Linux. Can you provide a standalone, compilable test case that reproduces the problem?

**Comment by 23paras** [comment]
class ORBUtil {

    private static final String JACORB = "JACORB";

    public static ORB getORB(String ip) {
        // TODO get this parameter from System
        return getORB(ip, "6337", (short) 9000, 10 * 1000, 10);
    }

    public static final ORB getORB(String host, String orbPort, short lpsPort, int shortTimeout, int longTimeout) {

        Properties props = new Properties();

        props.put("org.omg.CORBA.ORBInitialHost", host);
        props.put("org.omg.CORBA.ORBInitialPort", orbPort);

        String orbName = System.getProperty("com.lni.lps.orb");
        if (orbName == null) {
            orbName = JACORB;
        }

        if (orbName.equals(JACORB)) {
        	System.setProperty("jacorb.log.default.verbosity", "0");
    		initializeJacorbProperties(props, lpsPort);
        }

        ORB orb  = ORB.init(new String[] {}, props);
        return orb;
    } 



    private static final void initializeJacorbProperties(Properties props, short lpsPort) {

        String adaptorHostProp = "OAIAddr";
        props.put(adaptorHostProp, props.getProperty("org.omg.CORBA.ORBInitialHost"));

        String adaptorPortProp = "OAPort";
        props.put(adaptorPortProp, System.getProperty(adaptorPortProp, String.valueOf(lpsPort)));

        props.put("org.omg.CORBA.ORBClass", "org.jacorb.orb.ORB");

        Integer clientConnTimeout = Integer.getInteger("com.lni.lps.clientConnTimeout", 60000);

        Integer clientReplyTimeout = Integer.getInteger("com.lni.lps.clientReplyTimeout", 300000);

        props.put("jacorb.connection.client.pending_reply_timeout", clientReplyTimeout.toString());
        props.put("jacorb.connection.client.connect_timeout", clientConnTimeout.toString());

        props.put("jacorb.connection.server.timeout", clientReplyTimeout.toString());
    }

This is how we are creating the orb connection .

**Comment by 23paras** [comment]
[STUCK] ExecuteThread: '49' for queue: 'weblogic.kernel.Default (self-tuning)'
Stack Trace is:
java.lang.Thread.State: RUNNABLE
at java.net.PlainSocketImpl.socketConnect(Native Method)
at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
- locked <0x00000006e80c40e8> (a java.net.SocksSocketImpl)
at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
at java.net.Socket.connect(Socket.java:589)
at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:668)
at org.jacorb.security.ssl.sun_jsse.SSLSocketFactory.doCreateSocket(SSLSocketFactory.java:201)
at org.jacorb.orb.factory.AbstractSocketFactory.createSocket(AbstractSocketFactory.java:60)
at org.jacorb.orb.iiop.ClientIIOPConnection.createSocket(ClientIIOPConnection.java:315)
at org.jacorb.orb.iiop.ClientIIOPConnection.connect(ClientIIOPConnection.java:152)
- locked <0x00000007133cc120> (a org.jacorb.orb.iiop.ClientIIOPConnection)
at org.jacorb.orb.giop.GIOPConnection.sendMessage(GIOPConnection.java:1077)
- locked <0x0000000713445d88> (a java.lang.Object)
at org.jacorb.orb.giop.GIOPConnection.sendRequest(GIOPConnection.java:1022)
at org.jacorb.orb.giop.ClientConnection.sendRequest(ClientConnection.java:309)
at org.jacorb.orb.giop.ClientConnection.sendRequest(ClientConnection.java:290)
at org.jacorb.orb.Delegate._invoke_internal(Delegate.java:1373)
at org.jacorb.orb.Delegate.invoke_internal(Delegate.java:1210)
at org.jacorb.orb.Delegate.invoke(Delegate.java:1197)
at org.omg.CORBA.portable.ObjectImpl._invoke(ObjectImpl.java:475)

**Comment by rnc** [comment]
Can you reproduce this in a standalone project (maybe based on maven/gradle) that can be run to demonstrate the issue?
